# ========================================== CONAN YAML Configuration ==========================================
# This is a template YAML configuration file for CONAN v3.3.12
# PRIORS: Fix-F(val), Norm-N(mu,std), Uni-U(min,start,max), TruncNorm–(min,max,mu,std), LogUni-LU(min,start,max)

version           : 3.3.12
general:
  lc_filepath: Notebooks/TOI469/data/
  rv_filepath: Notebooks/TOI469/data/
  n_planet   : 3
  rv_unit    : m/s

photometry:
  auto_decorr:
    get_decorr  : False
    delta_bic   : -5
    exclude_cols: []
    exclude_pars: []
    enforce_pars: []
  light_curves:
    names        : [TOI-469_S06.dat, TOI-469_S33.dat]
    filters      : [T, T]
    wavelength_um: [0.8, 0.8]
    supersampling: [None, None]
    clip_outliers: [c1:W15C4n1, None]
    scale_columns: [None, None]
    spline       : [None, None]
    apply_jitter : [y, y]
    baseline:
      offset: [n, n]
      col0  : [0, 0]
      col3  : [0, 0]
      col4  : [0, 0]
      col5  : [0, 0]
      col6  : [0, 0]
      col7  : [0, 0]
      col8  : [0, 0]
  sinusoid:
    names: []
    trig : []
    n    : []
    par  : []
    P    : []
    amp  : []
    x0   : []
  gp:
    - lc_name     : all
      kernel      : [mat32]
      par         : [col0]
      h1_amp      : ['U(1,100,700)']
      h2_len_scale: ['U(0.1,1,20)']
      h3_other    : [None]
      h4_period   : [None]
      operation   : []
      gp_pck      : ce
  limb_darkening:
    filters: [T]
    q1     : ['N(0.3532,0.0153)']
    q2     : ['N(0.4032,0.0118)']
  tdv:
    fit_ddfs : n
    drprs    : 'U(-0.5,0,0.5)'
    div_white: n
  ttv:
    fit_ttvs       : n
    dt_priors      : 'U(-0.125, 0, 0.125)'
    baseline       : 0.25
    per_LC_T0      : False
    include_partial: True
  phase_curve:
    filters : [T]
    D_occ   : ['F(0)']
    Fn      : [None]
    ph_off  : [None]
    A_ev    : ['F(0)']
    f1_ev   : ['F(0)']
    A_db    : ['F(0)']
    pc_model: [cosine]
  custom_LC_function:
    function       : None
    x              : None
    func_pars      : None
    extra_args     : None
    op_func        : None
    replace_LCmodel: False
  contamination:
    filters      : [T]
    contam_factor: ['F(0)']

radial_velocity:
  auto_decorr:
    get_decorr  : False
    delta_bic   : -5
    exclude_cols: []
    exclude_pars: []
    enforce_pars: []
  rv_curves:
    names        : [TOI469rv1.dat, TOI469rv2.dat]
    scale_columns: [None, None]
    spline       : [None, None]
    apply_jitter : [y, y]
    baseline:
      gammas: ['N(81728,10)', 'N(81728,10)']
      col0  : [0, 0]
      col3  : [0, 0]
      col4  : [0, 0]
      col5  : [0, 0]
  gp:
    - rv_name     : same
      kernel      : [cos, expsq]
      par         : [col0, col0]
      h1_amp      : ['U(0.1,2,20)', 'F(-1)']
      h2_len_scale: ['U(0.01,1,100)', 'U(0.01,1,60)']
      h3_other    : None
      h4_period   : None
      h5_der_amp  : None
      error_col   : [col2, col2]
      operation   : ['*']
      gp_pck      : ge
  custom_RV_function:
    function       : None
    x              : None
    func_pars      : None
    extra_args     : None
    op_func        : None
    replace_RVmodel: False

planet_parameters:
  rho_star    : 'N(1.42,0.1)'
  Duration    : None
  RpRs        : ['U(0.001,0.0321,0.1)', 'U(0.001,0.0146,0.1)', 'U(0.001,0.0127,0.1)']
  Impact_para : ['U(0,0.28,1)', 'U(0,0.617,1)', 'U(0,0.273,1)']
  T_0         : ['U(2210.4,2210.634,2210.8)', 'U(2207.1,2207.252,2207.5)', 'U(2225.1,2225.259,2225.5)']
  Period      : ['U(13.6,13.63,13.7)', 'U(3.5,3.5379,3.6)', 'U(6.4,6.42975,6.5)']
  Eccentricity: ['F(0)', 'F(0)', 'F(0)']
  omega       : ['F(90)', 'F(90)', 'F(90)']
  sesinw      : None
  secosw      : None
  K           : ['U(0,2,10)', 'U(0,2,10)', 'U(0,2,10)']

stellar_parameters:
  radius_rsun : 'N(0.993, 0.034)'
  mass_msun   : 'N(0.88, 0.035)'
  input_method: Rrho

fit_setup:
  sampler                     : dynesty
  number_of_processes         : 10
  emcee_number_steps          : 2000
  leastsq_for_basepar         : n
  light_travel_time_correction: n
  emcee_number_chains         : 64
  emcee_burnin_length         : 500
  emcee_move                  : stretch
  dynesty_nlive               : 1000
  force_nlive                 : False
  dynesty_dlogz               : 0.1
  dynesty_nested_sampling     : static
  lc_jitter_loglims           : auto
  rv_jitter_lims              : auto
  lc_basecoeff_lims           : auto
  rv_basecoeff_lims           : auto
  apply_lc_gpndim_jitter      : y
  apply_rv_gpndim_jitter      : y
  apply_lc_gpndim_offset      : y
  apply_rv_gpndim_offset      : y
# ============ END OF FILE ============================================
