# ========================================== CONAN YAML Configuration ==========================================
# This is a YAML configuration file for CONAN v3.3.12
# PRIORS: Fix-'F(val)', Norm-'N(mu,std)', Uni-'U(min,start,max)', TruncNorm–'TN(min,max,mu,std)', LogUni-'LU(min,start,max)'

general:
  n_planet: 2

photometry:
  light_curves:
    filepath     : Notebooks/TOI-216/data/
    names        : [TOI-216_S1.dat, TOI-216_S2.dat, TOI-216_S3.dat, TOI-216_S6.dat, TOI-216_S4.dat, TOI-216_S5.dat]
    filters      : V
    wavelength_um: 0.6
    supersampling: None
    clip_outliers: c1:W15C5n3
    scale_columns: None
    spline       : None
    apply_jitter : y
    baseline:
      offset: y
      col0  : 0
      col3  : 0
      col4  : 0
      col5  : 0
      col6  : 0
      col7  : 0
      col8  : 0
  sinusoid:
    names: []
    trig : []
    n    : []
    par  : []
    P    : []
    amp  : []
    x0   : []
  gp:
    - lc_name     : same
      kernel      : [mat32]
      par         : [col0]
      h1_amp      : ['LU(1,2000,4000)']
      h2_len_scale: ['LU(0.1,1,30)']
      h3_other    : [None]
      h4_period   : [None]
      operation   : []
      gp_pck      : ce
  limb_darkening:
    filters: [V]
    q1     : ['U(0.0000,0.4400,1.0000)']
    q2     : ['U(0.0000,0.2400,1.0000)']
  tdv:
    fit_ddfs : n
    drprs    : 'U(-0.5,0,0.5)'
    div_white: n
  ttv:
    fit_ttvs       : y
    dt             : 'U(-0.1, 0, 0.1)'
    baseline       : 0.07
    per_LC_T0      : False
    include_partial: True
  phase_curve:
    filters : [V]
    D_occ   : ['F(0)']
    Fn      : [None]
    ph_off  : [None]
    A_ev    : ['F(0)']
    f1_ev   : ['F(0)']
    A_db    : ['F(0)']
    pc_model: [cosine]
  custom_LC_function:
    function       : None
    x              : None
    func_pars      : None
    extra_args     : None
    op_func        : None
    replace_LCmodel: False
  contamination:
    filters      : [V]
    contam_factor: ['F(0)']
  auto_decorr:
    get_decorr  : False
    delta_bic   : -5
    exclude_cols: []
    exclude_pars: []
    enforce_pars: []

radial_velocity:
  rv_curves:
    filepath     : /Users/tunde/Library/CloudStorage/OneDrive-unige.ch/mygit/CONAN/Notebooks/TOI-216/./data/
    rv_unit      : km/s
    names        : []
    scale_columns: []
    spline       : []
    apply_jitter : y
    baseline:
      gammas: []
      col0  : []
      col3  : []
      col4  : []
      col5  : []
  gp:
    - rv_name     : None
      kernel      : None
      par         : None
      h1_amp      : None
      h2_len_scale: None
      h3_other    : None
      h4_period   : None
      h5_der_amp  : None
      error_col   : None
      operation   : 
      gp_pck      : n
  custom_RV_function:
    function       : None
    x              : None
    func_pars      : None
    extra_args     : None
    op_func        : None
    replace_RVmodel: False
  auto_decorr:
    get_decorr  : False
    delta_bic   : -5
    exclude_cols: []
    exclude_pars: []
    enforce_pars: []

planet_parameters:
  rho_star    : 'N(2.38,0.1)'
  Duration    : None
  RpRs        : ['U(0.05,0.1,0.15)', 'U(0.05,0.1,0.15)']
  Impact_para : ['U(0.5,0.948,1.2)', 'U(0,0.15,0.5)']
  T_0         : ['F(1342.42819461)', 'F(1331.28531)']
  Period      : ['F(17.089)', 'F(34.556)']
  Eccentricity: ['F(0)', 'F(0)']
  omega       : ['F(90)', 'F(90)']
  sesinw      : None
  secosw      : None
  K           : ['F(0)', 'F(0)']

stellar_parameters:
  radius_rsun : None
  mass_msun   : None
  input_method: Rrho

fit_setup:
  sampler                     : dynesty
  number_of_processes         : 10
  emcee_number_steps          : 2000
  leastsq_for_basepar         : n
  light_travel_time_correction: n
  emcee_number_chains         : 64
  emcee_burnin_length         : 500
  emcee_move                  : stretch
  dynesty_nlive               : 150
  force_nlive                 : False
  dynesty_dlogz               : 0.1
  dynesty_nested_sampling     : static
  lc_jitter_loglims           : auto
  rv_jitter_lims              : auto
  lc_basecoeff_lims           : auto
  rv_basecoeff_lims           : auto
  apply_lc_gpndim_jitter      : n
  apply_rv_gpndim_jitter      : n
  apply_lc_gpndim_offset      : n
  apply_rv_gpndim_offset      : n
# ============ END OF FILE ============================================
