# ========================================== CONAN YAML Configuration ==========================================
# This is a YAML configuration file for CONAN v3.3.12
# PRIORS: Fix-'F(val)', Norm-'N(mu,std)', Uni-'U(min,start,max)', TruncNorm–'TN(min,max,mu,std)', LogUni-'LU(min,start,max)'

general:
  n_planet: 1

photometry:
  light_curves:
    filepath     : Notebooks/KELT-20/data/
    names        : [KELT-20_014101.dat, KELT-20_014102.dat, KELT-20_014103.dat]
    filters      : [CH1, CH2, CH3]
    wavelength_um: [0.1, 0.2, 0.3]
    supersampling: None
    clip_outliers: c1:W11C4n1
    scale_columns: med_sub
    spline       : None
    apply_jitter : y
    baseline:
      offset: y
      col0  : 0
      col3  : 0
      col4  : 0
      col5  : 0
      col6  : 0
      col7  : 1
      col8  : 1
  sinusoid:
    names: [same]
    trig : [sincos]
    n    : [3]
    par  : [col5]
    P    : ['F(360)']
    amp  : ['U(-2000,0,2000)']
    x0   : ['F(0)']
  gp:
    - lc_name     : None
      kernel      : None
      par         : None
      h1_amp      : None
      h2_len_scale: None
      h3_other    : None
      h4_period   : None
      op          : 
      gp_pck      : n
  limb_darkening:
    filters: [CH1, CH2, CH3]
    q1     : ['F(0)', 'F(0)', 'F(0)']
    q2     : ['F(0)', 'F(0)', 'F(0)']
  tdv:
    fit_ddfs : n
    drprs    : 'U(-0.5,0,0.5)'
    div_white: n
  ttv:
    fit_ttvs       : n
    dt             : 'U(-0.125, 0, 0.125)'
    baseline       : 0.25
    per_LC_T0      : False
    include_partial: True
  phase_curve:
    filters : [CH1, CH2, CH3]
    D_occ   : ['U(-100,0,300)', 'U(-100,0,300)', 'U(-100,0,300)']
    Fn      : [None, None, None]
    ph_off  : [None, None, None]
    A_ev    : ['F(0)', 'F(0)', 'F(0)']
    f1_ev   : ['F(0)', 'F(0)', 'F(0)']
    A_db    : ['F(0)', 'F(0)', 'F(0)']
    pc_model: [cosine, cosine, cosine]
  custom_LC_function:
    function       : None
    x              : None
    func_pars      : None
    extra_args     : None
    op_func        : None
    replace_LCmodel: False
  contamination:
    filters      : [CH1, CH2, CH3]
    contam_factor: ['F(0)', 'F(0)', 'F(0)']
  auto_decorr:
    get_decorr  : False
    delta_bic   : -5
    exclude_cols: []
    exclude_pars: []
    enforce_pars: []

radial_velocity:
  rv_curves:
    filepath     : Notebooks/KELT-20/data/
    rv_unit      : km/s
    names        : []
    scale_columns: []
    spline       : []
    apply_jitter : y
    baseline:
      gammas: []
      col0  : []
      col3  : []
      col4  : []
      col5  : []
  gp:
    - rv_name     : None
      kernel      : None
      par         : None
      h1_amp      : None
      h2_len_scale: None
      h3_other    : None
      h4_period   : None
      h5_der_amp  : None
      error_col   : None
      operation   : 
      gp_pck      : n
  custom_RV_function:
    function       : None
    x              : None
    func_pars      : None
    extra_args     : None
    op_func        : None
    replace_RVmodel: False
  auto_decorr:
    get_decorr  : False
    delta_bic   : -5
    exclude_cols: []
    exclude_pars: []
    enforce_pars: []

planet_parameters:
  rho_star    : None
  Duration    : 'F(0.13998861)'
  RpRs        : ['F(0.11572)']
  Impact_para : ['F(0.515)']
  T_0         : ['F(2406.9271740000695)']
  Period      : ['F(3.474074)']
  Eccentricity: ['F(0)']
  omega       : ['F(90)']
  sesinw      : None
  secosw      : None
  K           : ['F(0)']

stellar_parameters:
  radius_rsun : 'N(1.617, 0.05)'
  mass_msun   : None
  input_method: Rrho

fit_setup:
  sampler                     : dynesty
  number_of_processes         : 10
  emcee_number_steps          : 2000
  leastsq_for_basepar         : n
  light_travel_time_correction: n
  emcee_number_chains         : 64
  emcee_burnin_length         : 500
  emcee_move                  : stretch
  dynesty_nlive               : 200
  force_nlive                 : False
  dynesty_dlogz               : 0.1
  dynesty_nested_sampling     : static
  lc_jitter_loglims           : auto
  rv_jitter_lims              : auto
  lc_basecoeff_lims           : auto
  rv_basecoeff_lims           : auto
  apply_lc_gpndim_jitter      : y
  apply_rv_gpndim_jitter      : y
  apply_lc_gpndim_offset      : y
  apply_rv_gpndim_offset      : y
# ============ END OF FILE ============================================
