# ========================================== CONAN YAML Configuration ==========================================
# This is a template YAML configuration file for CONAN v3.3.12
# PRIORS: Fix-F(val), Norm-N(mu,std), Uni-U(min,start,max), TruncNorm–(min,max,mu,std), LogUni-LU(min,start,max)

version           : 3.3.12
general:
  lc_filepath: /Users/tunde/Library/CloudStorage/OneDrive-unige.ch/mygit/CONAN/Notebooks/WASP-127/WASP127_LC_RV/../data/
  rv_filepath: /Users/tunde/Library/CloudStorage/OneDrive-unige.ch/mygit/CONAN/Notebooks/WASP-127/WASP127_LC_RV/../data/
  n_planet   : 1
  rv_unit    : km/s

photometry:
  auto_decorr:
    get_decorr  : False
    delta_bic   : -5
    exclude_cols: []
    exclude_pars: []
    enforce_pars: []
  light_curves:
    names        : [lc6bjd.dat, WASP-127_S9.dat]
    filters      : [R, T]
    wavelength_um: [0.6, 0.8]
    supersampling: [None, 30]
    clip_outliers: [c1:W11C5n1, c1:W5C4.2n1]
    scale_columns: [med_sub, None]
    spline       : [None, None]
    apply_jitter : [y, y]
    baseline:
      offset: [y, y]
      col0  : [0, 0]
      col3  : [0, 0]
      col4  : [0, 0]
      col5  : [2, 0]
      col6  : [1, 0]
      col7  : [0, 0]
      col8  : [0, 0]
  sinusoid:
    names: []
    trig : []
    n    : []
    par  : []
    P    : []
    amp  : []
    x0   : []
  gp:
    - lc_name     : WASP-127_S9.dat
      kernel      : [mat32]
      par         : [col0]
      h1_amp      : ['LU(20,400,4000)']
      h2_len_scale: ['LU(0.007,0.4,5)']
      h3_other    : [None]
      h4_period   : [None]
      operation   : []
      gp_pck      : ce
  limb_darkening:
    filters: [R, T]
    q1     : ['N(0.4239,0.0253)', 'N(0.2978,0.0159)']
    q2     : ['N(0.3969,0.0166)', 'N(0.3784,0.0135)']
  tdv:
    fit_ddfs : n
    drprs    : 'U(-0.5,0,0.5)'
    div_white: n
  ttv:
    fit_ttvs       : n
    dt_priors      : 'U(-0.125, 0, 0.125)'
    baseline       : 0.25
    per_LC_T0      : False
    include_partial: True
  phase_curve:
    filters : [R, T]
    D_occ   : ['F(0)', 'F(0)']
    Fn      : [None, None]
    ph_off  : [None, None]
    A_ev    : ['F(0)', 'F(0)']
    f1_ev   : ['F(0)', 'F(0)']
    A_db    : ['F(0)', 'F(0)']
    pc_model: [cosine, cosine]
  custom_LC_function:
    function       : None
    x              : None
    func_pars      : None
    extra_args     : None
    op_func        : None
    replace_LCmodel: False
  contamination:
    filters      : [R, T]
    contam_factor: ['F(0)', 'F(0)']

radial_velocity:
  auto_decorr:
    get_decorr  : False
    delta_bic   : -5
    exclude_cols: []
    exclude_pars: []
    enforce_pars: []
  rv_curves:
    names        : [rv1.dat, rv2.dat]
    scale_columns: [med_sub, med_sub]
    spline       : [None, None]
    apply_jitter : [y, y]
    baseline:
      gammas: ['N(-9.229240663524008,0.1)', 'N(-9.210554832958305,0.1)']
      col0  : [2, 0]
      col3  : [1, 0]
      col4  : [1, 0]
      col5  : [0, 0]
  gp:
    - rv_name     : None
      kernel      : None
      par         : None
      h1_amp      : None
      h2_len_scale: None
      h3_other    : None
      h4_period   : None
      h5_der_amp  : None
      error_col   : None
      operation   : 
      gp_pck      : n
  custom_RV_function:
    function       : None
    x              : None
    func_pars      : None
    extra_args     : None
    op_func        : None
    replace_RVmodel: False

planet_parameters:
  rho_star    : 'N(0.565,0.035)'
  Duration    : None
  RpRs        : ['U(0.05,0.108,0.17)']
  Impact_para : ['U(0,0.29,1)']
  T_0         : ['N(6776.621239999775,0.001)']
  Period      : ['F(4.17806203)']
  Eccentricity: ['F(0)']
  omega       : ['F(90)']
  sesinw      : None
  secosw      : None
  K           : ['U(0,0.01,0.05)']

stellar_parameters:
  radius_rsun : 'N(1.33, 0.03)'
  mass_msun   : 'N(0.95, 0.02)'
  input_method: Rrho

fit_setup:
  sampler                     : dynesty
  number_of_processes         : 10
  emcee_number_steps          : 2000
  leastsq_for_basepar         : n
  light_travel_time_correction: n
  emcee_number_chains         : 64
  emcee_burnin_length         : 500
  emcee_move                  : stretch
  dynesty_nlive               : 100
  force_nlive                 : False
  dynesty_dlogz               : 0.1
  dynesty_nested_sampling     : static
  lc_jitter_loglims           : auto
  rv_jitter_lims              : auto
  lc_basecoeff_lims           : auto
  rv_basecoeff_lims           : auto
  apply_lc_gpndim_jitter      : n
  apply_rv_gpndim_jitter      : n
  apply_lc_gpndim_offset      : n
  apply_rv_gpndim_offset      : n
# ============ END OF FILE ============================================
