# ========================================== CONAN YAML Configuration ==========================================
# This is a template YAML configuration file for CONAN v3.3.12
# PRIORS: Fix-F(val), Norm-N(mu,std), Uni-U(min,start,max), TruncNorm–(min,max,mu,std), LogUni-LU(min,start,max)

version           : 3.3.12
general:
  lc_filepath: Notebooks/WASP-127/data/
  rv_filepath: Notebooks/WASP-127/data/
  n_planet   : 1
  rv_unit    : km/s

photometry:
  auto_decorr:
    get_decorr  : False
    delta_bic   : -5
    exclude_cols: []
    exclude_pars: []
    enforce_pars: []
  light_curves:
    names        : []
    filters      : []
    wavelength_um: []
    supersampling: []
    clip_outliers: []
    scale_columns: []
    spline       : []
    apply_jitter : [y]
    baseline:
      offset: []
      col0  : []
      col3  : []
      col4  : []
      col5  : []
      col6  : []
      col7  : []
      col8  : []
  sinusoid:
    names: []
    trig : []
    n    : []
    par  : []
    P    : []
    amp  : []
    x0   : []
  gp:
    - lc_name     : None
      kernel      : None
      par         : None
      h1_amp      : None
      h2_len_scale: None
      h3_other    : None
      h4_period   : None
      op          : 
      gp_pck      : n
  limb_darkening:
    filters: []
    q1     : []
    q2     : []
  tdv:
    fit_ddfs : n
    drprs    : 'U(-0.5,0,0.5)'
    div_white: n
  ttv:
    fit_ttvs       : n
    dt_priors      : 'U(-0.125, 0, 0.125)'
    baseline       : 0.25
    per_LC_T0      : False
    include_partial: True
  phase_curve:
    filters : []
    D_occ   : []
    Fn      : []
    ph_off  : []
    A_ev    : []
    f1_ev   : []
    A_db    : []
    pc_model: []
  custom_LC_function:
    function       : None
    x              : None
    func_pars      : None
    extra_args     : None
    op_func        : None
    replace_LCmodel: False
  contamination:
    filters      : []
    contam_factor: []

radial_velocity:
  auto_decorr:
    get_decorr  : False
    delta_bic   : -5
    exclude_cols: []
    exclude_pars: []
    enforce_pars: []
  rv_curves:
    names        : [rv1.dat, rv2.dat]
    scale_columns: [med_sub, med_sub]
    spline       : [None, None]
    apply_jitter : [y, y]
    baseline:
      gammas: ['N(-9.233510019201367,0.1)', 'N(-9.210554832955161,0.1)']
      col0  : [2, 0]
      col3  : [0, 0]
      col4  : [0, 0]
      col5  : [0, 0]
  gp:
    - rv_name     : None
      kernel      : None
      par         : None
      h1_amp      : None
      h2_len_scale: None
      h3_other    : None
      h4_period   : None
      h5_der_amp  : None
      error_col   : None
      operation   : 
      gp_pck      : n
  custom_RV_function:
    function       : None
    x              : None
    func_pars      : None
    extra_args     : None
    op_func        : None
    replace_RVmodel: False

planet_parameters:
  rho_star    : 'F(0)'
  Duration    : None
  RpRs        : ['F(0)']
  Impact_para : ['F(0)']
  T_0         : ['F(6776.621239999775)']
  Period      : ['F(4.17806203)']
  Eccentricity: ['F(0)']
  omega       : ['F(90)']
  sesinw      : None
  secosw      : None
  K           : ['U(0,0.01,0.1)']

stellar_parameters:
  radius_rsun : None
  mass_msun   : 'N(0.95, 0.02)'
  input_method: Mrho

fit_setup:
  sampler                     : dynesty
  number_of_processes         : 10
  emcee_number_steps          : 2000
  leastsq_for_basepar         : n
  light_travel_time_correction: n
  emcee_number_chains         : 64
  emcee_burnin_length         : 500
  emcee_move                  : stretch
  dynesty_nlive               : 100
  force_nlive                 : False
  dynesty_dlogz               : 0.1
  dynesty_nested_sampling     : static
  lc_jitter_loglims           : auto
  rv_jitter_lims              : auto
  lc_basecoeff_lims           : auto
  rv_basecoeff_lims           : auto
  apply_lc_gpndim_jitter      : y
  apply_rv_gpndim_jitter      : y
  apply_lc_gpndim_offset      : y
  apply_rv_gpndim_offset      : y
# ============ END OF FILE ============================================
